version: '3.1'
services:
  stats-server:
    build: ./ewm-stats
    image: ewm-stats
    container_name: ewm-stats
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "5090:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./ewm-main
    image: ewm-main
    container_name: ewm-main
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ewm-db
      - stats-server

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main-db
    ports:
      - "5080:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root