server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  banner:
    location: banner-test.txt

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.web: DEBUG

app:
  name: ewm-main
  stats-server-url: http://localhost:9090
  format:
    date: yyyy-MM-dd
    date-time: yyyy-MM-dd HH:mm:ss
