server:
  port: 9090

spring:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:ewm
  username: test
  password: test


app:
  name: ewm-stats
  format:
    date: yyyy-MM-dd
    date-time: yyyy-MM-dd HH:mm:ss
