server:
  port: 8080

spring:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:ewm
  username: test
  password: test


app:
  name: ewm-main
  stats-server-url: http://localhost:9090
  format:
    date: yyyy-MM-dd
    date-time: yyyy-MM-dd HH:mm:ss
