create table if not exists users
(
    user_id     bigint generated by default as identity not null,
    user_name   varchar(255)                            not null,
    email       varchar(255)                            not null,
    constraint pk_users primary key (user_id),
    constraint uc_users_email unique (email)
);

