server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  banner:
    location: banner-test.txt

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
    org: INFO

app:
  name: ewm-stats
  format:
    date: yyyy-MM-dd
    date-time: yyyy-MM-dd HH:mm:ss
